"""add room code

Revision ID: dddc6d924607
Revises: 5d32fe58eb6e
Create Date: 2026-06-20 18:24:42.630823

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dddc6d924607'
down_revision: Union[str, None] = '5d32fe58eb6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('code', sa.String(length=12), nullable=True))
        batch_op.create_index(batch_op.f('ix_rooms_code'), ['code'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rooms_code'))
        batch_op.drop_column('code')

    # ### end Alembic commands ###
