"""add hand cricket game

Revision ID: fe5542ecaf01
Revises: 8c3fdba1baa6
Create Date: 2026-06-20 21:13:41.511067

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe5542ecaf01'
down_revision: Union[str, None] = '8c3fdba1baa6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    bind = op.get_bind()
    dialect = bind.dialect.name
    if dialect == "postgresql":
        op.execute("ALTER TYPE gametype ADD VALUE IF NOT EXISTS 'hand_cricket'")
    elif dialect == "sqlite":
        with op.batch_alter_table("rooms", schema=None) as batch_op:
            batch_op.alter_column(
                "game_type",
                existing_type=sa.Enum("snakes_and_ladders", "ludo", "number_prediction", name="gametype"),
                type_=sa.Enum(
                    "snakes_and_ladders",
                    "ludo",
                    "number_prediction",
                    "hand_cricket",
                    name="gametype",
                ),
                existing_nullable=False,
            )

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hand_cricket_games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('in_progress', 'innings_break', 'finished', name='handcricketstatus'), nullable=False),
    sa.Column('balls_per_innings', sa.Integer(), nullable=False),
    sa.Column('innings', sa.Integer(), nullable=False),
    sa.Column('batsman_id', sa.Integer(), nullable=False),
    sa.Column('bowler_id', sa.Integer(), nullable=False),
    sa.Column('ball_number', sa.Integer(), nullable=False),
    sa.Column('player1_id', sa.Integer(), nullable=False),
    sa.Column('player2_id', sa.Integer(), nullable=False),
    sa.Column('player1_runs', sa.Integer(), nullable=False),
    sa.Column('player2_runs', sa.Integer(), nullable=False),
    sa.Column('innings1_runs', sa.Integer(), nullable=True),
    sa.Column('pending_batsman_fingers', sa.Integer(), nullable=True),
    sa.Column('pending_bowler_fingers', sa.Integer(), nullable=True),
    sa.Column('winner_id', sa.Integer(), nullable=True),
    sa.Column('is_tie', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['batsman_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['bowler_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['player1_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['player2_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['winner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('hand_cricket_games', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_hand_cricket_games_room_id'), ['room_id'], unique=True)

    op.create_table('hand_cricket_balls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('innings', sa.Integer(), nullable=False),
    sa.Column('ball_number', sa.Integer(), nullable=False),
    sa.Column('batsman_id', sa.Integer(), nullable=False),
    sa.Column('bowler_id', sa.Integer(), nullable=False),
    sa.Column('batsman_fingers', sa.Integer(), nullable=False),
    sa.Column('bowler_fingers', sa.Integer(), nullable=False),
    sa.Column('runs_scored', sa.Integer(), nullable=False),
    sa.Column('is_wicket', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['batsman_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['bowler_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['game_id'], ['hand_cricket_games.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('hand_cricket_balls', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_hand_cricket_balls_game_id'), ['game_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hand_cricket_balls', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hand_cricket_balls_game_id'))

    op.drop_table('hand_cricket_balls')
    with op.batch_alter_table('hand_cricket_games', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hand_cricket_games_room_id'))

    op.drop_table('hand_cricket_games')
    # ### end Alembic commands ###
